apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-pvc
  labels:
    logging-infra: support
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi

