#!/bin/bash

USER=${USER:-jcantril}

docker run -e USER=$USER -it --privileged \
    -v /home/jeff.cantrill/git:/opt/share/git \
    -v /home/jeff.cantrill/dist-git:/opt/share/dist-git \
    -v /home/jeff.cantrill/git.app:/opt/share/git.app \
    release_eng \
    /bin/bash

