#!/bin/bash
# https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash

# compare_versions takes two seminial versions and compares them
# return -1, 0, 1 depending of arg1 is less than, equal to,
#        or greater than arg2
compare_versions() {
    if [[ $1 == $2 ]]
    then
        echo 0
        return 0
    fi  
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do  
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do  
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            echo 1
            return 0
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            echo -1
            return 0
        fi
    done
    echo 0
    return 0
}
