apiVersion: v1
kind: Template
metadata:
  labels:
    app: log-generator
  name: log-generator
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: log-generator
    name: log-generator
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: log-generator
      deploymentconfig: log-generator
    template:
      metadata:
        labels:
          app: log-generator
          deploymentconfig: log-generator
      spec:
        containers:
        - image: ${IMAGE}
          imagePullPolicy: Always
          name: log-generator
          env:
          - name: MSG_SIZE
            value: "${MSG_SIZE}"
          - name: MSG_PER_SEC
            value: "${MSG_PER_SEC}"
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - log-generator
        from:
          kind: ImageStreamTag
          name: log-generator:latest
          namespace: openshift
      type: ImageChange
parameters:
- name: IMAGE
  value: openshift/log-generator
  required: true
- name: MSG_SIZE
  description: The max size of the message in bytes to generate
  value: "1000"
  required: true
- name: MSG_PER_SEC
  description: The rate of message generation
  value: "1"
  required: true
